# Generated by Django 3.2.25 on 2026-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0024_auto_20260523_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('C', 'COIN'), ('CH', 'CHAPTER'), ('V', 'VIP_SUBSCRIPTION')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'COIN'), ('CH', 'CHAPTER'), ('V', 'VIP_SUBSCRIPTION')], default='C', max_length=2),
        ),
    ]
